Exercise 8 and 9
lawli01/DevOps-Course-Starter pull request #8
Opened 2022-02-20 02:10 UTC by lawli01

Please make sure you are raising this PR against your own repository and not the original. If it says https://github.com/CorndelWithSoftwire in the search bar right now, you are in the wrong place!

Please also don't forget to submit the PR's url to Aptem afterwards (by clicking on the corresponding exercise component, pasting the url in the textbox that appears and then pressing the finish button).

2022-02-22 15:14 UTC, BenRamchandani requested changes
Hey, this looks like a good start to both M8 and M9, but there's some more to do for both.

To finish M8 you'll need to get GitHub actions deploying to Heroku, and for M9 you'll need to update your tests to work with Mongo.

2022-02-22 15:14 UTC, BenRamchandani commented on todo_app/data/item.py
> +            raise NotImplementedError
```suggestion
            raise NotImplementedError()
```
Throwing a class directly seems wrong, though I guess it works. Might also be worth providing an error message.

2022-03-18 16:45 UTC, hugh-emerson approved these changes
Your application is currently failing to load: 
http://todo-app-devopscourse.herokuapp.com/

Try checking the logs via the CLI or reach out to one of us if you need any extra help debugging it.

A guess at the issue would be environment variables in Heroku don't match the deployed version of the code, e.g.:
- Missing `MONGO_CONNECTION_STRING` or `MONGO_DATABASE_NAME`?
- Or you did set those in Heroku and deleted the Trello ones, but you haven't actually deployed the latest version of your code (since your pipeline only deploys from the main branch).

Approving PR because what you have here looks good.

2022-03-27 15:07 UTC, lawli01 commented on .github/workflows/my-ci-pipeline.yml
> +      EOF
I think I tried this and it didn't seem to work

2022-03-27 15:08 UTC, merged